"""
SQLAlchemy models for MatchLearn application.

This module defines the database schema including User, Resume,
JobDescription, GapAnalysis, LearningResource, and UserTask models.
"""

from datetime import datetime

from sqlalchemy import JSON, Column, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship

from backend.database import Base


class User(Base):
    """
    User model representing application users.

    Attributes:
        id: Primary key
        username: Unique username for login
        email: Unique email address
        hashed_password: Hashed password for authentication
        created_at: Timestamp when user was created
    """

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True, nullable=False)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    resumes = relationship("Resume", back_populates="user")
    gap_analyses = relationship("GapAnalysis", back_populates="user")
    tasks = relationship("UserTask", back_populates="user")


class Resume(Base):
    __tablename__ = "resumes"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))

    # Store parsed JSON for incremental updates
    # Structure: {"skills": ["Python", "Vue"], "projects": [...], "raw_text": "..."}
    structured_json = Column(JSON)
    raw_text = Column(Text)
    filename = Column(String, nullable=True)  # Original filename

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    user = relationship("User", back_populates="resumes")


class JobDescription(Base):
    __tablename__ = "job_descriptions"
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String)
    company = Column(String, nullable=True)

    # Store parsed requirements
    structured_json = Column(JSON)
    raw_text = Column(Text)

    created_at = Column(DateTime, default=datetime.utcnow)

    # Can be linked to multiple analyses
    gap_analyses = relationship("GapAnalysis", back_populates="job_description")


class GapAnalysis(Base):
    __tablename__ = "gap_analyses"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    resume_id = Column(Integer, ForeignKey("resumes.id"))
    job_description_id = Column(Integer, ForeignKey("job_descriptions.id"))

    overall_score = Column(Float)

    # Radar chart data: {"Python": 40, "Algorithm": 60, "Soft Skills": 80}
    radar_data = Column(JSON)

    # Detailed gap analysis and recommendations
    # Structure: [{"missing_skill": "FastAPI", "recommendation": "Learn route handling...", "resource_id": 101}]
    gap_details = Column(JSON)

    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="gap_analyses")
    resume = relationship("Resume")
    job_description = relationship("JobDescription", back_populates="gap_analyses")


class LearningResource(Base):
    __tablename__ = "learning_resources"
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String)
    source = Column(String)  # Bilibili, Coursera, GitHub
    url = Column(String)
    level = Column(String)  # Entry, Project, Advanced
    duration = Column(String)  # e.g., "3h", "2 weeks"
    tags = Column(JSON)  # ["Python", "Backend"]

    # Use simple count for ranking/popularity
    click_count = Column(Integer, default=0)

    tasks = relationship("UserTask", back_populates="resource")


class UserTask(Base):
    __tablename__ = "user_tasks"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    resource_id = Column(Integer, ForeignKey("learning_resources.id"))

    # Status: pending, in_progress, completed, verified
    status = Column(String, default="pending")

    # The specific skill this task is addressing
    skill_tag = Column(String)

    # Content generated by AI to be added to resume upon completion
    auto_fill_content = Column(Text, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)

    user = relationship("User", back_populates="tasks")
    resource = relationship("LearningResource", back_populates="tasks")
